version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: payment-api-db
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: user_api
      POSTGRES_PASSWORD: password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: